### PR TITLE
Improve the /list command.

### PR DESCRIPTION
**Pull request by sirnanos**
I thought the normal output for /list was ugly, so I made this. Enjoy!

### CODE REVIEW

**Comment by KarlOfDuty** [comment]
Thanks for the contribution, could you post a screenshot of the difference between your change and the original?

**Comment by KarlOfDuty** [comment]
Hm or actually, I used it myself now, I think the new markdown options in discord broke the formatting.

**Comment by sirnanos** [comment]
Before:
image
After:
image

You can basically tell the difference, before is all over the place and after is organised in a nice list. Would be nice to group them and actually use the buttons on the bottom tho.

**Review by KarlOfDuty — APPROVED** [review]
Not really sure when it was removed in the first place but well done finding it.

**Pull request merged**
